name: Build and Deploy API
on: [ "push", "pull_request" ]
jobs:
  fast-api-server-job:
    env:
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      HOST: ${{secrets.HOST}}
      DB_NAME: ${{secrets.DB_NAME}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DB_USER_TEST: ${{secrets.DB_USER_TEST}}
      DB_PASSWORD_TEST: ${{secrets.DB_PASSWORD_TEST}}
      HOST_TEST: ${{secrets.HOST_TEST}}
      DB_NAME_TEST: ${{secrets.DB_NAME_TEST}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v4
      - name: Installing python3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install dependencies from requirements.txt
        run: pip install -r requirements.txt
      - name: alembic upgrade DB
        run: alembic upgrade head
      - name: run pytest tests
        run: pytest -v --disable-warnings

  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres-server:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD_TEST}}
          POSTGRES_DB: ${{secrets.DB_NAME_TEST}}
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432