name: Build and Deploy API
on: [ "push", "pull_request" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v4
      - name: Installing python3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install dependencies from requirements.txt
        run: pip install -r requirements.txt